// <auto-generated />
using lab29_brian.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace lab29_brian.Migrations
{
    [DbContext(typeof(lab29_brianContext))]
    partial class lab29_brianContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("lab29_brian.Models.UserPost", b =>
                {
                    b.Property<int>("UserPostID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("GeoLocation");

                    b.Property<string>("Picture");

                    b.Property<string>("PostContent");

                    b.HasKey("UserPostID");

                    b.ToTable("UserPost");
                });
#pragma warning restore 612, 618
        }
    }
}
